config/routes.rb
IBlogBootstrap::Application.routes.draw do
  devise_for :users

	namespace :admin do
	  match '/', :to => "base#index"
    resources :articles
	end

  resources :articles, :only => [:index, :show] do
    resources :comments, :only => :create, :controller => 'articles/comments'
  end

  root :to => 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :name, :content, :published, :tag_list

  default_scope :order => 'created_at DESC'

  acts_as_taggable

  validates :name, :presence => true

  scope :recent, Article.where( :published => true ).limit(5)
  scope :published, Article.where( :published => true )
  scope :unpublished, Article.where(:published => false)

  def to_param 
    "#{id}-#{name.gsub(/\s|(,)/, '-')}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("created_at DESC") .page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.includes(:comments).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to [:admin, @article], :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to [:admin, @article], :notice => 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url, :notice => 'Article was successfully deleted.' }
      format.json { head :ok }
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_filter :authenticate_user!
	layout "dashboard"
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :articles_tags

  unless config.consider_all_requests_local
    rescue_from Exception, :with => :render_error
    rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found
    rescue_from ActionController::RoutingError, :with => :render_not_found
    rescue_from ActionController::UnknownController, :with => :render_not_found
    # customize these as much as you want, ie, different for every error or all the same
    rescue_from ActionController::UnknownAction, :with => :render_not_found
  end

  private

  def render_not_found(exception)
    #render :template => "/errors/404.html.erb", :status => 404
    redirect_to root_path
  end

  def render_error(exception)
    # you can insert logic in here too to log errors
    # or get more error info and use different templates
    #render :template => "/errors/500.html.erb", :status => 500
    redirect_to root_path
  end

  def articles_tags
    @tags = Article.tag_counts_on(:tags)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag]).page(params[:page])
    else
      @articles = Article.published.page(params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.includes(:comments).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def recent_articles
    Article.recent
  end

  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    syntax_highlighter(Redcarpet.new(text, *options).to_html).html_safe
      
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      # pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
      pre.replace CodeRay.scan(pre.text.rstrip, pre[:lang]).div
    end
    doc.to_s
  end

  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @article], :html => {:class => 'form-horizontal well'} do |f| %>
    <% if f.error_notification %>
        <div class="alert alert-error fade in">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= f.error_notification %>
        </div>
    <% end %>

    <table width="100%">
      <tr>
        <td><%= f.input :name, :input_html => {:class => "span6"} %></td>
      </tr>
      <tr>
        <td><%= f.input :published, :as => :boolean %></td>
      </tr>
      <tr>
        <td><%= f.input :content, :input_html => {:class => "span10"} %></td>
      </tr>
      <tr>
        <td><%= f.input :tag_list, :input_html => {:class => "span10"} %></td>
      </tr>
    </table>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn' %>
      <%= submit_tag 'Cancel', :type => :reset, :class => "btn" %>
    </div>
<% end %>

app/views/admin/articles/_sub_menu.html.erb
<% content_for :breadcrumb do %>
<ul class="breadcrumb">
    <% if params[:action] == "index" %>
        <li class="active"><span>文章列表</span></li>
    <% else %>
        <li><%= link_to "文章列表", admin_articles_path %></li>
    <% end %>
    <% if params[:action] == "new" %>
        <li class="active"><span>创建</span></li>
    <% else %>
        <li><%= link_to "创建", new_admin_article_path %></li>
    <% end %>
    <% if params[:action] == "edit" %>
        <li class="active"><span>修改</span></li>
    <% end %>
    <% if params[:action] == "show" %>
        <li class="active"><span>显示</span></li>    
    <% end %>
</ul>
<% end %>

app/views/admin/articles/edit.html.erb
<%= render "sub_menu" %>
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<% 'Artitles' %>
<%= render "sub_menu" %>
<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Name</th>
    <th>Published</th>
    <th>Created At</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.name, admin_article_path(article) %></td>
        <td><%= article.published %></td>
        <td><%= article.created_at.strftime('%Y-%m-%d') %></td>
        <td>
            <%= link_to 'Edit', edit_admin_article_path(article) %> | 
            <%= link_to "Destroy", [:admin, article], :confirm => 'Are you sure?', :method => :delete %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @articles %>

app/views/admin/articles/new.html.erb
<%= render "sub_menu" %>
<%= render 'form' %>

app/views/admin/articles/show.html.erb
<%= render "sub_menu" %>
<article>
  <header>
    <h1><%= @article.name %>
      <small><%= link_to "edit", edit_admin_article_path(@article) %></small>
      <small><%= link_to "Destroy", [:admin, @article], :confirm => 'Are you sure?', :method => :delete %></small>
    </h1>
  </header>

  <div>
    <div class="meta"><%= @article.created_at.strftime('%Y-%m-%d') %></div>
    <p>
      <%= markdown(@article.content) %>
    </p>
  </div>
</article>

app/views/admin/base/index.html.erb
<ul>
<li>总共发布了 <%= link_to Article.all.count, admin_articles_path %> 篇博客</li>
<li>草稿箱中有 <%= link_to Article.unpublished.count, admin_articles_path %> 篇文章未发表</li>
</ul>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
    <article>
      <h1><%= link_to article.name, article_path(article) %></h1>
      <div class="meta"><%= article.created_at.strftime('%Y-%m-%d') %></div>
      <p>
        <%= markdown(article.content) %>
      </p>
    </article>
<% end %>
<%= paginate @articles %>

app/views/articles/show.html.erb
<% title @article.name %>
<article>
  <header>
    <h1><%= @article.name %></h1>
  </header>

  <div>
    <div class="meta"><%= @article.created_at.strftime('%Y-%m-%d') %></div>
    <p>
      <%= raw(markdown(@article.content)) %>
    </p>
  </div>
</article>

app/views/layouts/_header.html.erb
<nav class="navbar-inner">
  <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="/">Leo的日志</a>

    <div class="nav-collapse">
      <ul class="nav"> 
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>     
      </ul>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Admin', admin_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, '#' %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class="sidebar span5 well">
  <ul class="widgets">
    <li id="recent-posts" class="widget-container widget_recent_entries">
      <h3 class="widget-title">Recent Posts</h3>
      <ul>
        <% for article in recent_articles %>
            <li><%= link_to article.name, article_path(article) %></li>
        <% end %>
      </ul>
    </li>
    <br/>
    <li id="tags" class="widget-container">
      <h3 class="widget-title">Tags</h3>
      <ul>
          <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
              <%= link_to tag.name, { :action => :index, :tag => tag.name }, :class => css_class %>
          <% end %>
      </ul>
    </li>
  </ul>
</nav>

app/views/layouts/admin/_header.html.erb
<nav class="navbar-inner">
  <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="/">Leo的日志</a>

    <div class="nav-collapse">
      <ul class="nav">
        <li class="active">
          <%= link_to 'Home', admin_path %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
            Articles
            <b class='caret'></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "List all articles", admin_articles_path %></li>
            <li><%= link_to "New article", new_admin_article_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Leo的日志" %></title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top">
  <%= render "layouts/header" %>
</header>

<div class="container master-container">
  <%= render "layouts/sidebar" %>
  <div class="content">
    <% if notice %>
        <div class="alert alert-success fade in" data-alert="alert">
          <a class="close" data-dismiss='alert' href="#">×</a>

          <p><%= notice %></p>
        </div>
    <% end %>

    <%= yield %>
  </div>
</div>
<footer>
  <%= Time.now.year %>
</footer>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Leo的日志" %></title>
  <%= stylesheet_link_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top">
  <%= render "layouts/admin/header" %>
</header>

<div class="container master-container">
  <div class="content">
    <% if notice %>
        <div class="alert alert-success fade in" data-alert="alert">
          <a class="close" data-dismiss='alert' href="#">×</a>

          <p><%= notice %></p>
        </div>
    <% end %>
    <%= yield :breadcrumb %>
    <%= yield %>
  </div>
</div>
<%= javascript_include_tag "application" %>
<%= debug(params) if  Rails.env.development? %>
</body>
</html>